/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package food;

import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.Vector;

/**
 *
 * @author gabor
 */
public class Calendar extends javax.swing.JFrame {

    /**
     * Creates new form Calendar
     */
    public Calendar() {
        initComponents();
        CreateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();

        jFrame1.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel1.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(jTable1.getModel());
        jTable1.setCellSelectionEnabled(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
          final int row = jTable1.getSelectedRow();
          final int column = jTable1.getSelectedColumn();
          Object data = (jTable1.getModel().getValueAt(row, column)).toString();
          System.out.println(data);
          jTextField1.setText((String) data);
          jLabel1.setText((String) data);
 
                jFrame1.setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked

 
    private void CreateTable(){
        
        int month =java.util.Calendar.getInstance().get(java.util.Calendar.MONTH);
        int year =java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
        
        java.util.Calendar cal = new GregorianCalendar();

	//System.out.println("\n"	+ cal.getDisplayName(java.util.Calendar.MONTH, java.util.Calendar.LONG,Locale.US) + " " + cal.get(java.util.Calendar.YEAR));

	int firstWeekdayOfMonth = cal.get(java.util.Calendar.DAY_OF_WEEK);
        //System.out.println(firstWeekdayOfMonth);

	int numberOfMonthDays = cal.getActualMaximum(java.util.Calendar.DAY_OF_MONTH);
        //System.out.println(numberOfMonthDays);
                
        int numberOfWeekDays = cal.getActualMaximum(java.util.Calendar.DAY_OF_WEEK_IN_MONTH);
        //System.out.println(numberOfWeekDays);

        Vector <Object> data = new Vector<>();                
        
        Vector <Object> week1 = new Vector<>();
        Vector <Object> week2 = new Vector<>();
        Vector <Object> week3 = new Vector<>();
        Vector <Object> week4 = new Vector<>();
        Vector <Object> week5 = new Vector<>();
        Vector <Object> week6 = new Vector<>();

        for (int i=1;i<=(firstWeekdayOfMonth-1);i++){
        week1.add("");        
        }
        for (int i=1;week1.size()<=6;i++){
        week1.add(i);        
        }
        
        int fdnw = (int) week1.lastElement()+1;
        for (int i=fdnw;week2.size()<=6;i++){
        week2.add(i);        
        }

        fdnw = (int) week2.lastElement()+1;
        for (int i=fdnw;week3.size()<=6;i++){
        week3.add(i);        
        }
        
        fdnw = (int) week3.lastElement()+1;
        for (int i=fdnw;week4.size()<=6&&i<=numberOfMonthDays;i++){
        week4.add(i);        
        }
        
        fdnw = (int) week4.lastElement()+1;
        for (int i=fdnw;week5.size()<=6&&i<=numberOfMonthDays;i++){
        week5.add(i);        
        }
        
        fdnw = (int) week5.lastElement()+1;
        for (int i=fdnw;week6.size()<=6&&i<=numberOfMonthDays;i++){
        week6.add(i);        
        }
            
        data.add(week1);
        data.add(week2);
        data.add(week3);
        data.add(week4);
        data.add(week5);
        data.add(week6);

        
        Vector <Object> header = new Vector<>();
        header.add("Su");
        header.add("Mo");
        header.add("Tu");
        header.add("We");
        header.add("Th");
        header.add("Fr");
        header.add("Sa");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(data,header));
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calendar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
